"""Activity splits schema models."""

from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field


class SplitSectionTypeSchema(BaseModel):
    id: Optional[int] = Field(
        default=None,
        title="Section Type ID",
        description="Numeric identifier for the split event section type.",
    )

    key: Optional[str] = Field(
        default=None,
        title="Section Type Key",
        description="Short key representing the section type.",
    )

    sectionTypeKey: Optional[str] = Field(
        default=None,
        title="Section Type Enum Key",
        description="Canonical enum-like section type key from Garmin.",
    )


class SplitEventSchema(BaseModel):
    startTimeGMT: Optional[str] = Field(
        default=None,
        title="Event Start Time GMT",
        description="Event timestamp in UTC, ISO 8601 format.",
    )

    startTimeGMTDoubleValue: Optional[float] = Field(
        default=None,
        title="Event Start Time GMT Milliseconds",
        description="Event start timestamp in Unix epoch milliseconds.",
    )

    sectionTypeDTO: Optional[SplitSectionTypeSchema] = Field(
        default=None,
        title="Section Type",
        description="Classification metadata for the event.",
    )


class LapSchema(BaseModel):
    model_config = ConfigDict(extra="allow")

    averageHR: Optional[float] = None
    averageMovingSpeed: Optional[float] = None
    averagePower: Optional[float] = None
    averageRunCadence: Optional[float] = None
    averageSpeed: Optional[float] = None
    averageTemperature: Optional[float] = None
    avgGradeAdjustedSpeed: Optional[float] = None
    bmrCalories: Optional[float] = None
    calories: Optional[float] = None
    connectIQMeasurement: Optional[list[dict[str, Any]]] = None
    directWorkoutComplianceScore: Optional[int] = None
    distance: Optional[float] = None
    duration: Optional[float] = None
    elapsedDuration: Optional[float] = None
    elevationGain: Optional[float] = None
    elevationLoss: Optional[float] = None
    endLatitude: Optional[float] = None
    endLongitude: Optional[float] = None
    groundContactTime: Optional[float] = None
    intensityType: Optional[str] = None
    lapIndex: Optional[int] = None
    lengthDTOs: Optional[list[dict[str, Any]]] = None
    maxElevation: Optional[float] = None
    maxHR: Optional[float] = None
    maxPower: Optional[float] = None
    maxRunCadence: Optional[float] = None
    maxSpeed: Optional[float] = None
    maxTemperature: Optional[float] = None
    maxVerticalSpeed: Optional[float] = None
    messageIndex: Optional[int] = None
    minElevation: Optional[float] = None
    minPower: Optional[float] = None
    minTemperature: Optional[float] = None
    movingDuration: Optional[float] = None
    normalizedPower: Optional[float] = None
    startLatitude: Optional[float] = None
    startLongitude: Optional[float] = None
    startTimeGMT: Optional[str] = None
    strideLength: Optional[float] = None
    totalWork: Optional[float] = None
    verticalOscillation: Optional[float] = None
    verticalRatio: Optional[float] = None
    wktIndex: Optional[int] = None
    wktStepIndex: Optional[int] = None


class ActivitySplitsSchema(BaseModel):
    activityId: Optional[int] = Field(
        default=None,
        title="Activity ID",
        description="Unique Garmin activity identifier for this split payload.",
    )

    lapDTOs: Optional[list[LapSchema]] = Field(
        default=None,
        title="Laps",
        description=(
            "Per-lap metrics for the activity. "
            "Laps can be auto-generated by Garmin based on distance or manually triggered by the user. "
            "Typically, laps are emitted at regular distance intervals (e.g. every 1 km during runs)."
        ),
    )

    eventDTOs: Optional[list[SplitEventSchema]] = Field(
        default=None,
        title="Events",
        description=(
            "Events emitted during the activity. "
            "These can include automatic events like warnings for heart rate or pace being outside of the planned range."
        ),
    )
